// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package com.arithmeticprotobuf.domain;

public final class Message {
  private Message() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_OperationData_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tutorial_OperationData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rmessage.proto\022\010tutorial\"\223\001\n\rOperationD" +
      "ata\022\023\n\013operatorOne\030\001 \002(\001\022\023\n\013operatorTwo\030" +
      "\002 \002(\001\0224\n\toperation\030\003 \002(\0162!.tutorial.Oper" +
      "ationData.Operation\"\"\n\tOperation\022\007\n\003sum\020" +
      "\000\022\014\n\010subtract\020\001B$\n\035com.arithmeticprotobu" +
      "f.domainP\001\240\001\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_tutorial_OperationData_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_tutorial_OperationData_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_tutorial_OperationData_descriptor,
              new java.lang.String[] { "OperatorOne", "OperatorTwo", "Operation", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
