// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: operations.proto

package com.arithmeticprotobuf.domain;

public final class Operations {
  private Operations() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface OperationDataOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required double operatorOne = 1;
    /**
     * <code>required double operatorOne = 1;</code>
     */
    boolean hasOperatorOne();
    /**
     * <code>required double operatorOne = 1;</code>
     */
    double getOperatorOne();

    // required double operatorTwo = 2;
    /**
     * <code>required double operatorTwo = 2;</code>
     */
    boolean hasOperatorTwo();
    /**
     * <code>required double operatorTwo = 2;</code>
     */
    double getOperatorTwo();

    // required .tutorial.OperationData.Operation operation = 3;
    /**
     * <code>required .tutorial.OperationData.Operation operation = 3;</code>
     */
    boolean hasOperation();
    /**
     * <code>required .tutorial.OperationData.Operation operation = 3;</code>
     */
    com.arithmeticprotobuf.domain.Operations.OperationData.Operation getOperation();
  }
  /**
   * Protobuf type {@code tutorial.OperationData}
   */
  public static final class OperationData extends
      com.google.protobuf.GeneratedMessage
      implements OperationDataOrBuilder {
    // Use OperationData.newBuilder() to construct.
    private OperationData(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private OperationData(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final OperationData defaultInstance;
    public static OperationData getDefaultInstance() {
      return defaultInstance;
    }

    public OperationData getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private OperationData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 9: {
              bitField0_ |= 0x00000001;
              operatorOne_ = input.readDouble();
              break;
            }
            case 17: {
              bitField0_ |= 0x00000002;
              operatorTwo_ = input.readDouble();
              break;
            }
            case 24: {
              int rawValue = input.readEnum();
              com.arithmeticprotobuf.domain.Operations.OperationData.Operation value = com.arithmeticprotobuf.domain.Operations.OperationData.Operation.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(3, rawValue);
              } else {
                bitField0_ |= 0x00000004;
                operation_ = value;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.arithmeticprotobuf.domain.Operations.internal_static_tutorial_OperationData_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.arithmeticprotobuf.domain.Operations.internal_static_tutorial_OperationData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.arithmeticprotobuf.domain.Operations.OperationData.class, com.arithmeticprotobuf.domain.Operations.OperationData.Builder.class);
    }

    public static com.google.protobuf.Parser<OperationData> PARSER =
        new com.google.protobuf.AbstractParser<OperationData>() {
      public OperationData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new OperationData(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<OperationData> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code tutorial.OperationData.Operation}
     */
    public enum Operation
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>sum = 0;</code>
       */
      sum(0, 0),
      /**
       * <code>subtract = 1;</code>
       */
      subtract(1, 1),
      ;

      /**
       * <code>sum = 0;</code>
       */
      public static final int sum_VALUE = 0;
      /**
       * <code>subtract = 1;</code>
       */
      public static final int subtract_VALUE = 1;


      public final int getNumber() { return value; }

      public static Operation valueOf(int value) {
        switch (value) {
          case 0: return sum;
          case 1: return subtract;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Operation>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Operation>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Operation>() {
              public Operation findValueByNumber(int number) {
                return Operation.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.arithmeticprotobuf.domain.Operations.OperationData.getDescriptor().getEnumTypes().get(0);
      }

      private static final Operation[] VALUES = values();

      public static Operation valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private Operation(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:tutorial.OperationData.Operation)
    }

    private int bitField0_;
    // required double operatorOne = 1;
    public static final int OPERATORONE_FIELD_NUMBER = 1;
    private double operatorOne_;
    /**
     * <code>required double operatorOne = 1;</code>
     */
    public boolean hasOperatorOne() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required double operatorOne = 1;</code>
     */
    public double getOperatorOne() {
      return operatorOne_;
    }

    // required double operatorTwo = 2;
    public static final int OPERATORTWO_FIELD_NUMBER = 2;
    private double operatorTwo_;
    /**
     * <code>required double operatorTwo = 2;</code>
     */
    public boolean hasOperatorTwo() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required double operatorTwo = 2;</code>
     */
    public double getOperatorTwo() {
      return operatorTwo_;
    }

    // required .tutorial.OperationData.Operation operation = 3;
    public static final int OPERATION_FIELD_NUMBER = 3;
    private com.arithmeticprotobuf.domain.Operations.OperationData.Operation operation_;
    /**
     * <code>required .tutorial.OperationData.Operation operation = 3;</code>
     */
    public boolean hasOperation() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required .tutorial.OperationData.Operation operation = 3;</code>
     */
    public com.arithmeticprotobuf.domain.Operations.OperationData.Operation getOperation() {
      return operation_;
    }

    private void initFields() {
      operatorOne_ = 0D;
      operatorTwo_ = 0D;
      operation_ = com.arithmeticprotobuf.domain.Operations.OperationData.Operation.sum;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasOperatorOne()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasOperatorTwo()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasOperation()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeDouble(1, operatorOne_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeDouble(2, operatorTwo_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeEnum(3, operation_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(1, operatorOne_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, operatorTwo_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, operation_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.arithmeticprotobuf.domain.Operations.OperationData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.arithmeticprotobuf.domain.Operations.OperationData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.arithmeticprotobuf.domain.Operations.OperationData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.arithmeticprotobuf.domain.Operations.OperationData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.arithmeticprotobuf.domain.Operations.OperationData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.arithmeticprotobuf.domain.Operations.OperationData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.arithmeticprotobuf.domain.Operations.OperationData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.arithmeticprotobuf.domain.Operations.OperationData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.arithmeticprotobuf.domain.Operations.OperationData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.arithmeticprotobuf.domain.Operations.OperationData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.arithmeticprotobuf.domain.Operations.OperationData prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tutorial.OperationData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.arithmeticprotobuf.domain.Operations.OperationDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.arithmeticprotobuf.domain.Operations.internal_static_tutorial_OperationData_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.arithmeticprotobuf.domain.Operations.internal_static_tutorial_OperationData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.arithmeticprotobuf.domain.Operations.OperationData.class, com.arithmeticprotobuf.domain.Operations.OperationData.Builder.class);
      }

      // Construct using com.arithmeticprotobuf.domain.Operations.OperationData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        operatorOne_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000001);
        operatorTwo_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000002);
        operation_ = com.arithmeticprotobuf.domain.Operations.OperationData.Operation.sum;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.arithmeticprotobuf.domain.Operations.internal_static_tutorial_OperationData_descriptor;
      }

      public com.arithmeticprotobuf.domain.Operations.OperationData getDefaultInstanceForType() {
        return com.arithmeticprotobuf.domain.Operations.OperationData.getDefaultInstance();
      }

      public com.arithmeticprotobuf.domain.Operations.OperationData build() {
        com.arithmeticprotobuf.domain.Operations.OperationData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.arithmeticprotobuf.domain.Operations.OperationData buildPartial() {
        com.arithmeticprotobuf.domain.Operations.OperationData result = new com.arithmeticprotobuf.domain.Operations.OperationData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.operatorOne_ = operatorOne_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.operatorTwo_ = operatorTwo_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.operation_ = operation_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.arithmeticprotobuf.domain.Operations.OperationData) {
          return mergeFrom((com.arithmeticprotobuf.domain.Operations.OperationData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.arithmeticprotobuf.domain.Operations.OperationData other) {
        if (other == com.arithmeticprotobuf.domain.Operations.OperationData.getDefaultInstance()) return this;
        if (other.hasOperatorOne()) {
          setOperatorOne(other.getOperatorOne());
        }
        if (other.hasOperatorTwo()) {
          setOperatorTwo(other.getOperatorTwo());
        }
        if (other.hasOperation()) {
          setOperation(other.getOperation());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasOperatorOne()) {
          
          return false;
        }
        if (!hasOperatorTwo()) {
          
          return false;
        }
        if (!hasOperation()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.arithmeticprotobuf.domain.Operations.OperationData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.arithmeticprotobuf.domain.Operations.OperationData) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required double operatorOne = 1;
      private double operatorOne_ ;
      /**
       * <code>required double operatorOne = 1;</code>
       */
      public boolean hasOperatorOne() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required double operatorOne = 1;</code>
       */
      public double getOperatorOne() {
        return operatorOne_;
      }
      /**
       * <code>required double operatorOne = 1;</code>
       */
      public Builder setOperatorOne(double value) {
        bitField0_ |= 0x00000001;
        operatorOne_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double operatorOne = 1;</code>
       */
      public Builder clearOperatorOne() {
        bitField0_ = (bitField0_ & ~0x00000001);
        operatorOne_ = 0D;
        onChanged();
        return this;
      }

      // required double operatorTwo = 2;
      private double operatorTwo_ ;
      /**
       * <code>required double operatorTwo = 2;</code>
       */
      public boolean hasOperatorTwo() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required double operatorTwo = 2;</code>
       */
      public double getOperatorTwo() {
        return operatorTwo_;
      }
      /**
       * <code>required double operatorTwo = 2;</code>
       */
      public Builder setOperatorTwo(double value) {
        bitField0_ |= 0x00000002;
        operatorTwo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double operatorTwo = 2;</code>
       */
      public Builder clearOperatorTwo() {
        bitField0_ = (bitField0_ & ~0x00000002);
        operatorTwo_ = 0D;
        onChanged();
        return this;
      }

      // required .tutorial.OperationData.Operation operation = 3;
      private com.arithmeticprotobuf.domain.Operations.OperationData.Operation operation_ = com.arithmeticprotobuf.domain.Operations.OperationData.Operation.sum;
      /**
       * <code>required .tutorial.OperationData.Operation operation = 3;</code>
       */
      public boolean hasOperation() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required .tutorial.OperationData.Operation operation = 3;</code>
       */
      public com.arithmeticprotobuf.domain.Operations.OperationData.Operation getOperation() {
        return operation_;
      }
      /**
       * <code>required .tutorial.OperationData.Operation operation = 3;</code>
       */
      public Builder setOperation(com.arithmeticprotobuf.domain.Operations.OperationData.Operation value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        operation_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .tutorial.OperationData.Operation operation = 3;</code>
       */
      public Builder clearOperation() {
        bitField0_ = (bitField0_ & ~0x00000004);
        operation_ = com.arithmeticprotobuf.domain.Operations.OperationData.Operation.sum;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:tutorial.OperationData)
    }

    static {
      defaultInstance = new OperationData(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:tutorial.OperationData)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_OperationData_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tutorial_OperationData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020operations.proto\022\010tutorial\"\223\001\n\rOperati" +
      "onData\022\023\n\013operatorOne\030\001 \002(\001\022\023\n\013operatorT" +
      "wo\030\002 \002(\001\0224\n\toperation\030\003 \002(\0162!.tutorial.O" +
      "perationData.Operation\"\"\n\tOperation\022\007\n\003s" +
      "um\020\000\022\014\n\010subtract\020\001B\037\n\035com.arithmeticprot" +
      "obuf.domain"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_tutorial_OperationData_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_tutorial_OperationData_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_tutorial_OperationData_descriptor,
              new java.lang.String[] { "OperatorOne", "OperatorTwo", "Operation", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
